### ISSUE TITLE
Plugin installed but no evidence of change

### ISSUE THREAD

**Issue by 3dprintedmac** [fieldOfView/Cura-ArcWelderPlugin#7] opened 2021-01-15 18:08 UTC
Just installed this plugin hoping to do the conversion from the cura side instead of octoprint so i can still print directly from cura to octoprint. I installed the plugin but not seeing any evidence of it. Should there be a menu option in Extensions? Should it be automatically converting my file when i send it? When i look at the gcode, it doesn't seem to have any G2 or g3 commands added, so doesn't appear to have changed anything.

Maybe i'm missing instructions somewhere on how to have it work, so any help or tips would be fantastic, thanks!

**Comment by 5axes** [comment] 2021-01-16 14:22
Did you activate in the special mode section the Arc Welder option ?
![image](https://user-images.githubusercontent.com/11015345/104814328-a078f480-580e-11eb-9785-ad67176238ea.png)

**Comment by fieldOfView** [comment] 2021-01-16 14:28
I'm closing this as a duplicate of #6. Please continue there.

**Closed as completed by fieldOfView** 2021-01-16 14:28 UTC
Labels: duplicate
