### ISSUE TITLE
Is it possible to enable it by default in a definitions file or only inside the plugin definition?

### ISSUE THREAD

**Issue by brunoosti** [fieldOfView/Cura-ArcWelderPlugin#19] opened 2021-05-18 02:01 UTC
Is it possible to enable it by default in a definitions file or only inside the plugin definition?
Couldn't make it work by only adding and  editing it in my base def.json file.
Thanks! : )

**Comment by fieldOfView** [comment] 2021-05-18 08:06
Duplicate of #17 

In short: no, that is not currently possible.

**Closed as completed by fieldOfView** 2021-05-18 08:06 UTC
Labels: duplicate
